### ISSUE TITLE
Cannot define artifacts

### ISSUE THREAD

**Issue by zatarra** [tomzo/gocd-json-config-plugin#17]
I've been trying to configure some jobs to save artifacts but it's doesn't seem to be working:

I've added the following snippet to one of the jobs:
```
          "artifacts": [
            {
              "artifact": {
                "src": "manifest.json",
                "dst": "manifests"
              }
            }
          ]
```

But the plugin breaks with the following error:
```runtime; - Unexpected error when handling plugin response java.lang.NullPointerException```

If I check the logs I can see this:

```
2018-08-17 17:05:43,035 ERROR [100@MessageListener for ConfigMaterialUpdater] GoRepoConfigDataSource:148 - Failed to parse configuration material https://**********@github.com/*************** by Plugin json.config.plugin
com.thoughtworks.go.plugin.access.configrepo.InvalidPartialConfigException:
runtime;
	- Unexpected error when handling plugin response
java.lang.NullPointerException
	at com.thoughtworks.go.config.ConfigRepoPlugin.parseDirectory(ConfigRepoPlugin.java:58)
	at com.thoughtworks.go.config.ConfigRepoPlugin.load(ConfigRepoPlugin.java:46)
	at com.thoughtworks.go.config.GoRepoConfigDataSource.onCheckoutComplete(GoRepoConfigDataSource.java:136)
	at com.thoughtworks.go.server.materials.ConfigMaterialUpdater.updateConfigurationFromCheckout(ConfigMaterialUpdater.java:106)
	at com.thoughtworks.go.server.materials.ConfigMaterialUpdater.onMessage(ConfigMaterialUpdater.java:91)
	at com.thoughtworks.go.server.materials.ConfigMaterialUpdater.onMessage(ConfigMaterialUpdater.java:38)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
	at java.lang.Thread.run(Thread.java:748)
```

Can anyone shed some light on how to use this?

**Comment by arvindsv** [comment]
I think @tomzo is on vacation.

Looking at the [example here](https://github.com/tomzo/gocd-json-config-plugin#job), shouldn't it be this, instead?

```json
{
  "name": "pipeline-name",
  "environment_variables": [],
  "artifacts": [
    {
      "src": "manifest.json",
      "dst": "manifests",
      "type": "build"
    },
    {
      "src": "second-artifact.json",
      "dst": "some-dest",
      "type": "build"
    }
  ]
}
```

**Comment by zatarra** [comment]
You are right. Just a small correction: the "src" key is actually "source" otherwise GoCD (v18.7.0) com complains about the lack of the source attribute. Thanks :)
